operators, quoted strings, etc
cedlang/ced pull request #5
Opened 2022-04-16 20:08 UTC by SuperLeaf1995

2022-04-16 20:15 UTC, aa2006 approved these changes

2022-04-16 20:58 UTC, NineSilver requested changes
Using abort() isn't a good idea if we want to report errors to the user.
Because we are using string views it isn't necessary to check for '\0'.
I don't see the point on treating comments as tokens, as we aren't parsing nor making anything with them.

2022-04-16 21:13 UTC, SuperLeaf1995 commented
> Using abort() isn't a good idea if we want to report errors to the user. Because we are using string views it isn't necessary to check for '\0'. I don't see the point on treating comments as tokens, as we aren't parsing nor making anything with them.

We can save comments for debug information

2022-04-17 19:15 UTC, segfaultdev requested changes
holy fuck are you ok

2022-04-17 19:15 UTC, segfaultdev commented on src/lexer.c
> +    [TOK_BIT_OR] = "||",
p sure you got these names wrong

2022-04-17 19:15 UTC, segfaultdev commented on src/lexer.c
> +    [TOK_COMMENT] = "comment",
please not

2022-04-17 19:15 UTC, segfaultdev commented on src/lexer.c
> +
could be smaller but ig its fine

2022-04-17 19:15 UTC, segfaultdev commented on src/lexer.c
> +
COMMENTS ARE NOT TOKENS

2022-04-17 19:15 UTC, segfaultdev commented on src/lexer.c
> +
in fact, the function reading chars should skip comments entirely

2022-04-21 07:19 UTC, unsafecast reviewed
@segfaultdev is pretty much on point.

2022-07-22 03:04 UTC, closed without merging